# Generated by Django 4.1.1 on 2022-09-15 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('arrived_at', models.DateTimeField(auto_now_add=True, verbose_name='arrived at')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='weight')),
                ('height', models.PositiveSmallIntegerField(verbose_name='height')),
                ('identifying_mark', models.CharField(blank=True, max_length=250, verbose_name='identifying_mark')),
            ],
            options={
                'verbose_name': 'animal',
                'verbose_name_plural': 'animals',
            },
        ),
        migrations.CreateModel(
            name='ShelterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='shelter')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animalmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'shelter',
                'verbose_name_plural': 'shelters',
            },
        ),
    ]
